Repository Senity-Waved/Waved_BE, pull requests merged in 2024-03, with the labels that each got.

#6 Refactor: JWT 토큰을 이용한 인증과 인증 예외 처리 및 accessToken 만료 시 재발급 로직 구현
  src/main/java/com/senity/waved/base/config/WebSecurityConfig.java
  src/main/java/com/senity/waved/base/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/base/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/senity/waved/base/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/senity/waved/base/jwt/JwtFilter.java
  src/main/java/com/senity/waved/base/jwt/JwtSecurityConfig.java
  src/main/java/com/senity/waved/base/jwt/TokenProvider.java
  src/main/java/com/senity/waved/base/redis/Redis.java
  src/main/java/com/senity/waved/base/redis/RedisProperties.java
  src/main/java/com/senity/waved/base/redis/RedisUtil.java
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/java/com/senity/waved/domain/member/service/MemberService.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#8 Feat: 회원가입 커스터마이징 기능 구현
  src/main/java/com/senity/waved/base/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/base/redis/Redis.java
  src/main/java/com/senity/waved/base/redis/RedisRepository.java
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/java/com/senity/waved/domain/member/dto/MemberJoinDto.java
  src/main/java/com/senity/waved/domain/member/entity/Gender.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
  src/main/java/com/senity/waved/domain/member/service/MemberService.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
Labels: ✨ Feature

#10 Feat: 로그아웃 및 중복 로그인 예외 처리, Redis 블랙리스트 설정
  src/main/java/com/senity/waved/base/config/RedisConfig.java
  src/main/java/com/senity/waved/base/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/base/jwt/BlackListedTokenException.java
  src/main/java/com/senity/waved/base/jwt/JwtFilter.java
  src/main/java/com/senity/waved/base/jwt/TokenProvider.java
  src/main/java/com/senity/waved/base/redis/RedisProperties.java
  src/main/java/com/senity/waved/base/redis/RedisRepository.java
  src/main/java/com/senity/waved/base/redis/RedisUtil.java
  src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/java/com/senity/waved/domain/member/dto/MemberJoinDto.java
  src/main/java/com/senity/waved/domain/member/entity/Gender.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/exception/MultipleLoginException.java
  src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
  src/main/java/com/senity/waved/domain/member/service/MemberService.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
Labels: 💡 enhancement, ✨ Feature

#13 Chore: 챌린지 관련 패키지 구조 추가
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/Challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/Challenge/repository/ChallengeRepository.java
  src/main/java/com/senity/waved/domain/Challenge/service/ChallengeService.java
  src/main/java/com/senity/waved/domain/Challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/myChallenge/controller/myChanllengeController.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/Status.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
Labels: ✨ Feature

#14 Feat: 회원 정보 수정, 깃허브 연동 기능 구현
  build.gradle
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/Challenge/repository/ChallengeRepository.java
  src/main/java/com/senity/waved/domain/Challenge/service/ChallengeService.java
  src/main/java/com/senity/waved/domain/Challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/ChanllengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challenge/entity/ChallengeType.java
  src/main/java/com/senity/waved/domain/challenge/entity/VerificationType.java
  src/main/java/com/senity/waved/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeService.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/java/com/senity/waved/domain/member/dto/GithubInfoDto.java
  src/main/java/com/senity/waved/domain/member/dto/ProfileEditDto.java
  src/main/java/com/senity/waved/domain/member/dto/response/ProfileInfoResponseDto.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/exception/InvalidRefreshTokenException.java
  src/main/java/com/senity/waved/domain/member/exception/WrongGithubInfoException.java
  src/main/java/com/senity/waved/domain/member/service/MemberService.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/exception/MemberNotFoundException.java
Labels: ✨ Feature

#17 Feat: 챌린지 인증방식 기능 구현
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/exception/ChallengeGroupNotFoundException.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
  src/main/java/com/senity/waved/domain/quiz/dto/response/QuizResponseDto.java
  src/main/java/com/senity/waved/domain/quiz/entity/Quiz.java
  src/main/java/com/senity/waved/domain/quiz/exception/QuizNotFoundException.java
  src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizService.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/controller/VerificationController.java
  src/main/java/com/senity/waved/domain/verification/dto/request/VerificationRequestDto.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/exception/ChallengeGroupVerificationException.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/GithubApi.java
  src/main/java/com/senity/waved/domain/verification/service/GithubService.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationService.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: ✨ Feature

#21 Feat: 테스트 데이터 생성
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challenge/entity/ChallengeType.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/review/entity/Review.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 💡 enhancement

#23 Feat: 챌린지 인증 내역 조회 및 인증 방식 업데이트
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/controller/MyChallengeController.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/exception/MyChallengeNotFoundException.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/quiz/dto/response/QuizResponseDto.java
  src/main/java/com/senity/waved/domain/quiz/entity/Quiz.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/dto/request/VerificationRequestDto.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
  src/main/resources/data.sql
Labels: ✨ Feature

#25 Feature: 챌린지 그룹 상세 페이지 조회 및 예외 커스터마이징
  src/main/java/com/senity/waved/WavedApplication.java
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeService.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/exception/ChallengeGroupNotCompletedException.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/myChallenge/controller/MyChallengeController.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/ChallengeStatus.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/exception/AlreadyMyChallengeExistsException.java
  src/main/java/com/senity/waved/domain/myChallenge/exception/MyChallengeNotFoundException.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/senity/waved/domain/review/entity/Review.java
  src/main/java/com/senity/waved/domain/review/exception/AlreadyReviewedException.java
  src/main/java/com/senity/waved/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/senity/waved/domain/review/repository/ReviewRepository.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/resources/data.sql
Labels: ✨ Feature

#27 Fix: 생성자 초기화 되도록 수정
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
Labels: 🐞 BugFix

#28 Feat: 깃허브 연동 여부 확인 및 인증 업데이트 기능 구현
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: 💡 enhancement, ✨ Feature

#29 Refactor: 챌린지 인증 방식 중복 불가능 하도록 리팩토링
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/exception/AlreadyVerifiedException.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#31 Fix: 멤버 정보 입력 여부 필드 추가
  src/main/java/com/senity/waved/base/config/WebSecurityConfig.java
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/base/jwt/TokenDto.java
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: 🐞 BugFix, 💡 enhancement

#34 Feat: 인증 좋아요 기능 구현
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/liked/controller/LikedController.java
  src/main/java/com/senity/waved/domain/liked/dto/response/LikedResponseDto.java
  src/main/java/com/senity/waved/domain/liked/entity/Liked.java
  src/main/java/com/senity/waved/domain/liked/exception/DuplicationLikeException.java
  src/main/java/com/senity/waved/domain/liked/exception/LikeNotAuthorizedException.java
  src/main/java/com/senity/waved/domain/liked/repository/LikedRepository.java
  src/main/java/com/senity/waved/domain/liked/service/LikedService.java
  src/main/java/com/senity/waved/domain/liked/service/LikedServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/exception/VerificationNotFoundException.java
  src/main/java/com/senity/waved/domain/verification/exception/VerifyExistenceOnDate.java
Labels: ✨ Feature

#36 Fix: Front token 전달 형식 변경 및 데이터베이스 자동 종료 문제 해결
  src/main/java/com/senity/waved/base/config/WebSecurityConfig.java
  src/main/java/com/senity/waved/base/security/OAuth2MemberSuccessHandler.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/resources/application.yml
  src/main/resources/log4jdbc.log4j2.properties
Labels: 🐞 BugFix

#40 Fix: 인증 내역 조회에서 nickname 필드 반환하도록 수정
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
Labels: 🐞 BugFix

#42 Feat: 관리자 API 구현
  src/main/java/com/senity/waved/domain/admin/controller/AdminController.java
  src/main/java/com/senity/waved/domain/admin/service/AdminService.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/AdminVerificationListDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
  src/main/resources/data.sql
Labels: ✨ Feature

#46 Fix: 타입 변경 및 리뷰 수정 데이터 조회 API
  src/main/java/com/senity/waved/common/BaseEntity.java
  src/main/java/com/senity/waved/common/ZonedDateTimeConverter.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/VerificationListResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/quiz/dto/response/QuizResponseDto.java
  src/main/java/com/senity/waved/domain/quiz/entity/Quiz.java
  src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/senity/waved/domain/review/controller/ReviewController.java
  src/main/java/com/senity/waved/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/senity/waved/domain/review/service/ReviewService.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/controller/VerificationController.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
  src/main/resources/data.sql
Labels: 🐞 BugFix, 💡 enhancement

#47 Feat: 결제 시스템 API 기능 구현
  build.gradle
  src/main/java/com/senity/waved/base/config/IamportClientConfig.java
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/paymentRecord/controller/PaymentRecordController.java
  src/main/java/com/senity/waved/domain/paymentRecord/dto/request/PaymentRequestDto.java
  src/main/java/com/senity/waved/domain/paymentRecord/entity/PaymentRecord.java
  src/main/java/com/senity/waved/domain/paymentRecord/entity/PaymentStatus.java
  src/main/java/com/senity/waved/domain/paymentRecord/exception/DepositAmountNotMatchException.java
  src/main/java/com/senity/waved/domain/paymentRecord/exception/MemberAndMyChallengeNotMatch.java
  src/main/java/com/senity/waved/domain/paymentRecord/repository/PaymentRecordRepository.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordService.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ✨ Feature

#51 Fix: payment 테스트
  src/main/java/com/senity/waved/base/config/WebSecurityConfig.java
  src/main/java/com/senity/waved/base/jwt/JwtFilter.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/entity/PaymentRecord.java
  src/main/resources/data.sql
Labels: 🐞 BugFix, 🔨 Refactor

#52 Refactor: 챌린지 환급 여부/달성 여부 반환 및 리뷰 서비스 예외 처리
  src/main/java/com/senity/waved/base/jwt/JwtFilter.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: 🐞 BugFix, 💡 enhancement, ✨ Feature

#54 Refcator: 결제 검증 API 예치금 리팩토링
  build.gradle
  src/main/java/com/senity/waved/base/config/IamportClientConfig.java
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🔨 Refactor

#55 Fix: iamport 연동
  build.gradle
  src/main/java/com/senity/waved/base/config/IamportClientConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#57 Feat: 내 인증 내역 조회 & 날짜별 기술 면접 문제 조회 API
  src/main/java/com/senity/waved/domain/challengeGroup/controller/ChallengeGroupController.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupService.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyVerifsResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizService.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/controller/VerificationController.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#60 Refactor: 리뷰 조회 및 예치금 반환 수정
  src/main/java/com/senity/waved/domain/admin/controller/AdminController.java
  src/main/java/com/senity/waved/domain/admin/service/AdminService.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/controller/ChallengeController.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeService.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/AdminChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/member/controller/MemberController.java
  src/main/java/com/senity/waved/domain/member/service/MemberService.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/java/com/senity/waved/domain/review/dto/response/ChallengeReviewResponseDto.java
  src/main/java/com/senity/waved/domain/review/dto/response/MemberReviewResponseDto.java
  src/main/java/com/senity/waved/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/senity/waved/domain/review/entity/Review.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#64 Feat: 페이지네이션 적용 및 최신순 정렬
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/member/service/MemberServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/dto/response/PaymentRecordResponseDto.java
  src/main/java/com/senity/waved/domain/paymentRecord/entity/PaymentRecord.java
  src/main/java/com/senity/waved/domain/paymentRecord/repository/PaymentRecordRepository.java
  src/main/java/com/senity/waved/domain/review/repository/ReviewRepository.java
Labels: 🔨 Refactor

#67 Bug: 객체 매핑 수정 및 관리자 인증 취소 기능 예외 처리
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challenge/exception/ChallengeNotFoundException.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/controller/MyChallengeController.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeService.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/exception/MemberAndMyChallengeNotMatch.java
  src/main/java/com/senity/waved/domain/paymentRecord/exception/MemberAndMyChallengeNotMatchException.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/entity/Verification.java
  src/main/java/com/senity/waved/domain/verification/exception/FailedVerificationException.java
  src/main/java/com/senity/waved/domain/verification/exception/VerifyExistenceOnDate.java
  src/main/java/com/senity/waved/domain/verification/exception/VerifyExistenceOnDateException.java
  src/main/java/com/senity/waved/domain/verification/exception/VerifyNonexistenceOnDateException.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: 🐞 BugFix

#69 Refactor: 필요없는 Null 값 정리 및 신청 후 결제 여부 확인하는 필드 추가
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeCompletedDto.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeProgressDto.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
Labels: 💡 enhancement, 🔨 Refactor

#72 Fix: 무료 챌린지 재신청 가능하도록 수정
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
Labels: 🐞 BugFix
