Repository Senity-Waved/Waved_BE, pull requests merged in 2024-04, with the labels that each got.

#76 Feat: 챌린지 그룹 생성 스케줄링 및 알림 도메인 추가
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/entity/ChallengeGroup.java
  src/main/java/com/senity/waved/domain/challengeGroup/repository/ChallengeGroupRepository.java
  src/main/java/com/senity/waved/domain/notification/controller/NotificationController.java
  src/main/java/com/senity/waved/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/senity/waved/domain/notification/entity/Notification.java
  src/main/java/com/senity/waved/domain/notification/repository/NotificationRepository.java
  src/main/java/com/senity/waved/domain/notification/service/NotificationService.java
  src/main/java/com/senity/waved/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
Labels: ✨ Feature

#78 Feat: 실시간 알림 기능 구현
  build.gradle
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/event/controller/EventController.java
  src/main/java/com/senity/waved/domain/event/repository/EventRepository.java
  src/main/java/com/senity/waved/domain/event/service/EventService.java
  src/main/java/com/senity/waved/domain/event/service/EventServiceImpl.java
  src/main/java/com/senity/waved/domain/member/entity/Member.java
  src/main/java/com/senity/waved/domain/myChallenge/repository/MyChallengeRepository.java
  src/main/java/com/senity/waved/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/service/VerificationServiceImpl.java
  src/test/java/com/senity/waved/data.sql
Labels: ✨ Feature

#80 Feat: 알림 삭제 로직 추가 및 관리자 탈퇴 서버 관련 문제 해결
  src/main/java/com/senity/waved/base/exception/GlobalExceptionHandler.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/event/controller/EventController.java
  src/main/java/com/senity/waved/domain/notification/controller/NotificationController.java
  src/main/java/com/senity/waved/domain/notification/repository/NotificationRepository.java
  src/main/java/com/senity/waved/domain/notification/service/NotificationService.java
  src/main/java/com/senity/waved/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/exception/AlreadyDeletedVerificationException.java
  src/main/java/com/senity/waved/domain/verification/repository/VerificationRepository.java
Labels: 🐞 BugFix, ✨ Feature

#82 Refactor: 챌린지 대표 이미지 url 변경 및 테스트 주간 챌린지 반영
  src/main/java/com/senity/waved/domain/challenge/entity/Challenge.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/test/java/com/senity/waved/data.sql
Labels: 🔨 Refactor

#84 Fix: 참여자수 변경 로직 수정 및 imageUrl 전달 방식 변경
  src/main/java/com/senity/waved/base/jwt/TokenProvider.java
  src/main/java/com/senity/waved/base/security/CustomOAuth2UserService.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/service/ChallengeGroupServiceImpl.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
Labels: 🐞 BugFix

#86 Refactor: 서버 타임 리팩토링
  src/main/java/com/senity/waved/common/ZonedDateTimeConverter.java
  src/main/java/com/senity/waved/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/senity/waved/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/AdminChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupHomeResponseDto.java
  src/main/java/com/senity/waved/domain/challengeGroup/dto/response/ChallengeGroupResponseDto.java
  src/main/java/com/senity/waved/domain/liked/repository/LikedRepository.java
  src/main/java/com/senity/waved/domain/member/repository/MemberRepository.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeCompletedDto.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeProgressDto.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyChallengeResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/dto/response/MyVerifsResponseDto.java
  src/main/java/com/senity/waved/domain/myChallenge/entity/MyChallenge.java
  src/main/java/com/senity/waved/domain/myChallenge/service/MyChallengeServiceImpl.java
  src/main/java/com/senity/waved/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/com/senity/waved/domain/paymentRecord/dto/response/PaymentRecordResponseDto.java
  src/main/java/com/senity/waved/domain/paymentRecord/service/PaymentRecordServiceImpl.java
  src/main/java/com/senity/waved/domain/quiz/repository/QuizRepository.java
  src/main/java/com/senity/waved/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/senity/waved/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/senity/waved/domain/verification/dto/response/LinkVerificationResponseDto.java
  src/main/java/com/senity/waved/domain/verification/dto/response/PictureVerificationResponseDto.java
  src/main/java/com/senity/waved/domain/verification/dto/response/TextVerificationResponseDto.java
  src/main/java/com/senity/waved/domain/verification/service/GithubService.java
Labels: 🐞 BugFix, 🔨 Refactor
